# Generated by Django 3.1.1 on 2020-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ko_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('profile_path', models.CharField(max_length=255, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ko_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('profile_path', models.CharField(max_length=255, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('movie', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('genre_string', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('actor_string', models.CharField(max_length=255)),
                ('director_string', models.CharField(max_length=30)),
                ('budget', models.FloatField(null=True)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.CharField(max_length=30)),
                ('revenue', models.FloatField(null=True)),
                ('runtime', models.FloatField(null=True)),
                ('spoken_language', models.CharField(max_length=30)),
                ('tagline', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('actor', models.ManyToManyField(null=True, related_name='actor_movies', to='movie.Actor')),
                ('director', models.ManyToManyField(null=True, related_name='director_movies', to='movie.Director')),
                ('genre', models.ManyToManyField(null=True, related_name='genre_movies', to='movie.Genre')),
            ],
        ),
    ]
